function captureException(error: Error): void {
    console.error(error);
}

export { captureException };
